#!/bin/bash

# Function to generate a random password
generate_password() {
    local length=$1
    if [[ -z $length ]]; then
        length=12
    fi

    # Generate password using /dev/urandom
    tr -dc '[:alnum:]' < /dev/urandom | head -c "$length"
}

# Function to initialize Git repository, add files, commit, and push changes
git_integration() {
    # Initialize Git repository
    git init
    git add README.md generate_password.sh
    git commit -m "Add generate_password.sh script"
    git branch -M main
    git remote add origin https://github.com/Gh0stWh15p3r/Bash-script.git
    git push -u origin main
}

# Main function
main() {
    echo "Generating a random password..."
    echo "Your password is: $(generate_password)"

    # Call Git integration function
    git_integration
}

# Call the main function
main
